acearchive/artifact-submissions

submissions/hernandez-asexual-protagonists.json
=> [Submission] Asexual Protagonists: What Their Patterns Reveal About the Representation of Asexuality

submissions/t-pagan-guerra-library-of-asexual-nonfiction.json
=> [Proposal] Nonfiction Book List

submissions/sennkestra-asexual-research-bibliography.json
Update the media type of the Bibtex file to `text/x-bibtex` and update the URL of the Zotero library to point directly to the library instead of to the group page
=> [Edit] Asexual research bibliography

submissions/solanas-the-scum-manifesto.json
=> [Submission] The SCUM Manifesto

submissions/aint-i-a-woman-vol-1-no-8.json
=> [Submission] Ain't I a Woman, vol. 1, no. 8

submissions/nederland-asexuals-have-problems-too.json, submissions/village-voice-asexuals-have-problems-too.json
=> [Submission] Asexuals Have Problems Too

submissions/village-voice-afraid-to-ask.json
=> [Submission] Afraid to Ask

submissions/gay-liberator-transsexual-liberation.json
=> [Submission] Detroit Gay Liberator

submissions/tweedie-sexual-roles.json
=> [Submission] Sexual Roles Historically Stressed To Serve Society

submissions/barton-all-gods-children.json
=> [Submission] All God's Children

submissions/aint-i-a-woman-vol-1-no-8.json, submissions/fifth-estate-vol-9-no-4.json
=> [Submission] Fifth Estate

submissions/the-conspiracy-sexual-law-reporter.json
=> [Submission] SexualLaw Reporter

submissions/the-news-dispatch-helen-help-us.json
=> [Submission] Helen Help Us!

submissions/bentler-typology-of-transsexualism.json
=> [Submission] Typology of Transsexualism

submissions/macneil-lehrer-briggs-initiative.json
=> [Submission] The Briggs Initiative

submissions/dullea-lack-of-sexual-desire.json
=> [Submission] A Lack of Sexual Desire Emerges as a Contemporary Condition

submissions/bell-asexuality-everybodys-not-doing.json
=> [Submission] Asexuality: Everybody's Not Doing It

submissions/coyote-aro-throwback-hour.json
=> [Submission] Aro Throwback Hour

submissions/berkeley-barb-no-more-sex.json
=> [Submission] Berkeley Barb

submissions/tennov-love-and-limerence.json
=> [Submission] Love and Limerence

submissions/asexuality-dot-net.json
This PR makes a trivial change to an artifact to test the artifact upload workflow.
=> Test the artifact upload workflow

submissions/feminist-dialogue-world-of-women.json
=> World of Women; Speeches from the Lesbian Feminist Dialogue Conference

submissions/landers-not-a-freak.json
=> [Submission] This guy's not a freak, he's just asexual

submissions/florence-times-victims-laid-out.json
=> [Submission] Victims Laid Out Like Egyptian Book Of Dead

submissions/nurius-mental-health-implications.json
=> [Submission] Mental Health Implications of Sexual Orientation

submissions/landers-asexual-man-needs-counseling.json
=> [Submission] Asexual Man Needs Counseling, Not Advice

submissions/landers-lack-of-interest.json
=> [Submission] St. Louis Woman Needs Therapy To Deal With Lack of Interest

submissions/sanello-high-concept-movies.json
=> [Submission] In pursuit of high-concept movies

submissions/white-a-sexual-glossary.json
=> [Submission] A Sexual Glossary

submissions/blanchard-nonhomosexual-gender-dysphorias.json
=> [Submission] The classification and labeling of nonhomosexual gender dysphorias

submissions/bryja-committed-asexual-relationships.json
=> [Submission] Committed, Loving, yet Asexual Relationships

submissions/chalmers-morrissey-flowers-again.json
=> [Submission] Morrissey flowers again

submissions/bentler-typology-of-transsexualism.json
This PR adds content warnings to a transphobic paper, as suggested in acearchive/acearchive.lgbt#3.
=> [Edit] A Typology of Transsexualism: Gender Identity Theory and Data

submissions/landers-lack-of-interest.json
This PR adds a content warning, as suggested in acearchive/acearchive.lgbt#3.
=> [Edit] "St. Louis Woman Needs Therapy"

submissions/landers-asexual-man-needs-counseling.json
This PR adds a content warning, as suggested in acearchive/acearchive.lgbt#3.
=> [Edit] "Asexual Man Needs Counseling"

submissions/florence-times-victims-laid-out.json
=> [Edit] "Victims Laid Out Like Egyptian Book of Dead"

submissions/toby-on-sally.json
=> [Edit] Toby on Sally

submissions/ru-dot-antisex.json
=> [Edit] RU.Antisex

submissions/blanchard-nonhomosexual-gender-dysphorias.json
=> [Edit] “The Classification and Labeling of Nonhomosexual Gender Dysphorias”

submissions/haven-for-the-human-amoeba.json
=> [Edit] "Haven for the Human Amoeba"

submissions/lawrence-atypical-sexualities.json
=> [Edit] “Atypical sexualities face oppression”

submissions/david-jay-tucker.json
=> [Edit] David Jay on Tucker

submissions/david-jay-the-view.json
=> [Edit] David Jay on The View

.github/ISSUE_TEMPLATE/proposal.yaml
=> Add content warnings field to issue template

submissions/hirschfeld-sexualpathologie.json
- Add a content warning
- Add additional identities to the identity list
=> [Edit] Sexualpathologie

submissions/landers-dismayed-parent.json
=> [Submission] "Teacher's message dismays a parent"

submissions/tv-guise-vol-1-iss-9.json
=> [Submission] TV Guise, vol. 1, iss. 9

submissions/tv-guise-vol-1-iss-9.json
=> [Edit] "TV Guise," vol. 1, iss. 9

submissions/kasper-married-couples-enjoy-celibacy.json
=> [Submission] "Some married couples enjoy celibacy"

submissions/kasper-married-couples-enjoy-celibacy.json
=> [Edit] "Some married couples enjoy celibacy"

submissions/horie-die-a-virgin.json
=> [Submission] I plan to die a virgin.

submissions/gender-flex-vol-4-iss-23.json
=> [Submission] *Gender Flex*, vol. 4, iss. 23

submissions/gender-flex-vol-3-iss-19.json
=> [Submission] *Gender Flex*, vol. 3, iss. 19

submissions/bullough-human-sexuality.json
=> [Submission] Human Sexuality: An Encyclopedia

submissions/usenet-asexual-discussion-groups-ask.json
=> [Submission] Usenet "Asexuality"

submissions/stein-mismeasure-of-desire.json
=> [Submission] *The Mismeasure of Desire: The Science, Theory, and Ethics of Sexual Orientation*

submissions/eserver-sexual-glossary.json
=> [Submission] "Glossary of Sexual Terms"

submissions/liber-between-mental-health.json
=> [Submission] "Between Mental Health and Mental Disease"

submissions/transvestia-vol-9-no-52.json
=> [Submission] *Transvestia*, vol. 9, no. 52

submissions/tit-bits-the-spinsters-prize.json
=> [Submission] "The Spinsters' Prize"

submissions/hammond-sexual-impotence.json, submissions/linda-baker-self-marriage.json, submissions/tharunka-sex-survey.json, submissions/woroni-bisexuality.json
Proposed in #130, #131, #132, #133
=> [Submission] Add multiple submissions from luciellaes

submissions/aus-wd-sexuality-poster.json
=> [Submission] Sexuality: An AUS Women's Department Poster

submissions/kaye-falling-in-love.json
=> [Submission] "Is Falling In Love a Health Hazard?"

submissions/tross-freie-liebe.json, submissions/trosse-ein-weib.json, submissions/trosse-freie-liebe.json
=> [Submission] *Ist "freie Liebe" Sittenlosigkeit?*

submissions/new-view-campaign.json
=> [Submission] The New View Campaign

submissions/aus-wd-sexuality-pamphlet.json, submissions/aus-wd-sexuality-poster.json
=> [Submission] *Sexuality*: An AUS Women's Department Pamphlet

submissions/camp-ink-monday-conference.json
=> [Submission] *CAMP INK*, vol. 4, no. 5

submissions/trosse-kontrarsexualismus.json
=> [Submission] *Der Konträrsexualismus inbezug auf Ehe und Frauenfrage*
